export function buildTutorialGenerationPrompt(params: {
  examName: string;
  nodeTitle: string;
  parentContext: string;
  description: string | undefined;
  keyTerms: string[];
  difficultyLevel: "introductory" | "intermediate" | "advanced";
}): { systemPrompt: string; prompt: string } {
  const systemPrompt = `You are a world-class educator creating comprehensive study material for Indian competitive examination preparation. You write tutorials that are detailed enough for self-study, with clear explanations, practical examples, and exam-relevant focus.

Your tutorials must be:
- Comprehensive: cover everything a student needs to know for the exam
- Clear: use simple language, build from basics to advanced
- Exam-focused: highlight what examiners typically ask
- India-specific: use Indian pharmacopoeia, Indian healthcare examples, Indian regulatory bodies where relevant
- Structured: clear sections with headings, definitions, examples`;

  const prompt = `Generate a comprehensive tutorial for exam preparation.

Exam: ${params.examName}
Topic: ${params.nodeTitle}
Parent context: ${params.parentContext}
${params.description ? `Syllabus description: ${params.description}` : ""}
Key terms to cover: ${params.keyTerms.join(", ") || "None specified"}
Target difficulty: ${params.difficultyLevel}

The tutorial must include these sections:
1. LEARNING OBJECTIVES — What the student will understand after reading
2. INTRODUCTION — Brief overview and why this topic matters
3. DETAILED EXPLANATION — Core content broken into logical sub-sections
4. KEY DEFINITIONS — Every important term defined clearly
5. FORMULAS — Any relevant formulas with derivation/explanation (if applicable)
6. EXAMPLES — Worked examples or case studies
7. CLINICAL/PRACTICAL APPLICATIONS — Real-world relevance
8. IMPORTANT POINTS FOR EXAM — Frequently tested concepts, common mistakes
9. SUMMARY — Concise recap of key takeaways
10. MNEMONICS — Memory aids for complex lists/classifications (if helpful)
11. REFERENCES — Standard textbook references

For BPharm/Pharmacy exams, reference:
- Remington's Pharmaceutical Sciences
- Lachman's Theory and Practice of Industrial Pharmacy
- Rang & Dale's Pharmacology / KD Tripathi's Pharmacology
- Indian Pharmacopoeia (IP)

OUTPUT FORMAT: JSON matching TutorialContentSchema (provided via Instructor.js)`;

  return { systemPrompt, prompt };
}

export function buildTutorialMergePrompt(
  providerResults: Array<{ provider: string; tutorialJson: string }>,
): { systemPrompt: string; prompt: string } {
  const systemPrompt = `You are merging tutorial content generated by multiple AI providers into a single comprehensive tutorial. Your job is to:
1. Keep ALL unique information from each provider
2. Remove redundant/duplicate explanations (keep the clearer version)
3. Maintain a consistent tone and structure
4. Add attribution comments where content differs significantly
5. Prefer more detailed explanations over brief ones
6. If providers disagree on facts, flag the disagreement for human review`;

  const providerSections = providerResults
    .map((r) => `PROVIDER: ${r.provider}\n${r.tutorialJson}`)
    .join("\n\n");

  const prompt = `Merge the following tutorial versions into one comprehensive tutorial.

${providerSections}

Rules:
- The merged tutorial should be MORE comprehensive than any single version
- Keep the best definitions, examples, and explanations from each
- If one provider has a mnemonic and others don't, include it
- If providers have different examples, include all (up to 3 per concept)
- Structure must match TutorialContentSchema

OUTPUT: Merged JSON matching TutorialContentSchema`;

  return { systemPrompt, prompt };
}
